- name: Create DB Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-secret
        namespace: lms
      type: Opaque
      data:
        password: "{{ 'admin12345' | b64encode }}"
