---
- name: Create DB Secret in Kubernetes using db-sa service account
  hosts: n1  # Make sure the target machine is correct
  become: false
  gather_facts: false
  collections:
    - kubernetes.core  # Ensure kubernetes.core is included

  tasks:
    - name: Create PostgreSQL Secret using db-sa service account
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: postgres-secret
            namespace: lms
          type: Opaque
          data:
            password: "{{ 'admin12345' | b64encode }}"
        auth:
          service_account: db-sa  # Specify the service account
          namespace: lms
