apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: lms  # Ensure the namespace is correct
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      serviceAccountName: db-sa  # Specify the service account to be used for the deployment
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Ensure the secret name is correct
                  key: password
