- name: Install Kubernetes Python module if missing
  hosts: n1
  become: yes
  tasks:
    - name: Ensure pip3 is installed
      package:
        name: python3-pip
        state: present

    - name: Ensure kubernetes module is installed
      ansible.builtin.pip:
        name: kubernetes
        executable: pip3
