---
- name: Create namespace and service accounts using kubectl
  hosts: n1  # your target from inventory
  become: false
  gather_facts: false

  vars:
    namespace: lms
    service_accounts:
      - db-sa
      - app-sa
      - web-sa

  tasks:
    - name: Create LMS namespace (if not exists)
      shell: |
        kubectl get namespace {{ namespace }} || kubectl create namespace {{ namespace }}

    - name: Create service accounts
      shell: |
        kubectl create serviceaccount {{ item }} -n {{ namespace }} || echo "SA {{ item }} already exists"
      loop: "{{ service_accounts }}"
